### ISSUE TITLE
[Index manager] Handle indexer uploading files

### ISSUE THREAD

**Issue by datzero9** [massbitprotocol/massbitprotocol#24]
Currently, user will upload these files through IPFS: compiled library file (*.so, *.dll, *.rlib), graphql schema (.graphql), project config (.yaml)
- Save library file for later plugin manager loading (plugin manager is dependent on `libloading`, which required local file path)
- Parse graphql file to generate associated migration and run it, maybe provide schema for DB store.
- Parse config file to get information for later indexer triggers.
```graphql
type BlockTs @entity {
  id: ID!
  blockHeight: BigInt!
  timestamp: Date!
}

```

```yaml
specVersion: "0.0.1"
description: "This subquery indexes timestamp of each block"
repository: "https://github.com/subquery/subql-examples"

schema: "./schema.graphql"

dataSources:
  - name: runtime
    kind: substrate
    startBlock: 1
    mapping:
      handlers:
        - handler: handleTimestampSet
          kind: substrate/BlockHandler
```
