### ISSUE TITLE
plugin-indexing logic

### ISSUE THREAD

**Issue by daywednes** [massbitprotocol/massbitprotocol#8]
1. Common library for end-user to index: blockchain data types (substrate), lib to store data into postgres
2. design plugin template sample for end-user
3. gen-code if needed
4. compile the code to sol type for dynamic loading
5. testing: indexing simulation

**Comment by daywednes** [comment]
1. data schema (schema.graphql)
2. plugin.yaml as follows

```
specVersion: "0.0.1"
description: "This massbit indexes timestamp of each block"
repository: "https://github.com/subquery/subql-examples"

schema: "./schema.graphql"

network: substrate

dataSources:
  - name: runtime
    kind: substrate/Runtime
    startBlock: 1
    mapping:
      handlers:
        - handler: handleTimestampSet
          kind: substrate/CallHandler
          filter:
            module: timestamp
            method: set
```
